[MENUS]
Menu1=VENDO
Menu2=PISOTAB

[VENDO]
Items=Adopisoft,JuanFi,PisoFi,TaraKifi,WiFi5Soft,LPB

[PISOTAB]
Items=JuanFi,PisonetX

; Details for items under PISOTAB

[PISOTAB_JuanFi]
Node= ESP8266
Version= 4.5
Part=2
Offseat=0x0000000, 0x200000
Wireless=True
LanBased=True

[PISOTAB_PisonetX]
Node= ESP8266, ESP32
Version= 4.5
Part=2
Offseat=0x0000000, 0x200000
Wireless=True
LanBased=True



; Details for items under VENDO
[VENDO_Adopisoft]
Node= ESP8266
Version= 1.0.5
Part=1
Offseat=0x000000
Wireless=True
LanBased=False

[VENDO_JuanFi]
Node= ESP8266
Version= 4.5
Part=2
Offseat=0x0000000, 0x200000
Wireless=True
LanBased=True

[VENDO_PisoFi]
Node= ESP8266
Version= 4.5
Part=1
Offseat=0x00000
Wireless=True
LanBased=False

[VENDO_TaraKiFi]
Node= ESP8266
Version= 1.81.3
Part=1
Offseat=0x00000
Wireless=True
LanBased=True

[VENDO_Wifi5Soft]
Node= ESP8266, ESP32
Version= 4.4
Part=1
Offseat=0x00000
Wireless=True
LanBased=False

[VENDO_LPB]
Node= ESP8266
Version= 1.0.2
Part=1
Offseat=0x00000
Wireless=True
LanBased=False

