[MENUS]
Menu1=VENDO
Menu2=PISOTAB

[VENDO]
Items=AdoPisoft,EzWifi1.2,EzWifi2.3,FastFi-ActiveHigh,FastFi-ActiveLow,JuanFi,Kitifi-MtBasedv2.2,Kitifi-MtBasedv1.3.6,Kitifi-MtBasedv1.3.6-ESP32,Kitifi-OpenWRT,LPB1.5,LPB2.0,PisoFi,TaraKifi-MiniPC,TaraKifi-OpenWRT,TaraKifi-OPI,Wifi5soft,Wifi5Soft-ESP32
[PISOTAB]
Items=FastFi-ESP32,FastFi-with_SmartCharging,FastFi-with_SmartChargingESP32,JuanFi,PisonetX



; Details for items under PISOTAB
[PISOTAB_FastFi-ESP32]
Node= ESP32
Version= 2.5.1
Part=1
Offseat=0x0000000
Wireless=True
LanBased=False

[PISOTAB_FastFi-with_SmartCharging]
Node= ESP8266
Version= 2.5.1
Part=1
Offseat=0x0000000
Wireless=True
LanBased=False

[PISOTAB_FastFi-with_SmartChargingESP32]
Node= ESP32
Version= 2.5.1
Part=1
Offseat=0x0000000
Wireless=True
LanBased=False

[PISOTAB_JuanFi]
Node= ESP8266
Version= 4.5
Part=2
Offseat=0x0000000, 0x200000
Wireless=True
LanBased=True

[PISOTAB_PisonetX]
Node= ESP32
Version= 2.3.3
Part=1
Offseat=0x0000000
Wireless=True
LanBased=False

; Details for items under VENDO
[VENDO_Adopisoft]
Node= ESP8266
Version= 1.0.5
Part=1
Offseat=0x000000
Wireless=True
LanBased=False

[VENDO_EzWifi1.2]
Node= ESP32
Version= 1.2
Part=4
Offseat=0xe000,0x1000,0x10000,0x8000
Wireless=True
LanBased=False

[VENDO_EzWifi2.3]
Node= ESP32
Version= 2.3
Part=4
Offseat=0xe000,0x1000,0x10000,0x8000
Wireless=True
LanBased=False

[VENDO_FastFi-ActiveHigh]
Node= ESP8266
Version= 2.5.1
Part=1
Offseat=0x000000
Wireless=True
LanBased=False

[VENDO_FastFi-ActiveLow]
Node= ESP8266
Version= 2.5.1
Part=1
Offseat=0x000000
Wireless=True
LanBased=False

[VENDO_JuanFi]
Node= ESP8266
Version= 4.5
Part=2
Offseat=0x0000000, 0x200000
Wireless=True
LanBased=True

[VENDO_Kitifi-MtBasedv2.2]
Node= ESP8266
Version= 2.2
Part=1
Offseat=0x0000000
Wireless=True
LanBased=True

[VENDO_Kitifi-MtBasedv1.3.6]
Node= ESP32,ESP8266
Version= 1.3.6
Part=1
Offseat=0x0000000
Wireless=True
LanBased=True

[VENDO_Kitifi-OpenWRT]
Node= ESP8266
Version= 2.2
Part=1
Offseat=0x0000000
Wireless=True
LanBased=True

[VENDO_LPB1.5]
Node= ESP8266
Version= 1.0.4
Part=1
Offseat=0x00000
Wireless=True
LanBased=False

[VENDO_LPB2.0]
Node= ESP8266
Version= 1.0.2
Part=1
Offseat=0x00000
Wireless=True
LanBased=False


[VENDO_PisoFi]
Node= ESP8266
Version= 4.5
Part=1
Offseat=0x00000
Wireless=True
LanBased=False

[VENDO_TaraKifi-MiniPC]
Node= ESP8266
Version= 1.81.3
Part=1
Offseat=0x00000
Wireless=True
LanBased=True

[VENDO_TaraKifi-OpenWRT]
Node= ESP8266
Version= 1.81.3
Part=1
Offseat=0x00000
Wireless=True
LanBased=True

[VENDO_TaraKifi-OPI]
Node= ESP8266
Version= 1.81.3
Part=1
Offseat=0x00000
Wireless=True
LanBased=True

[VENDO_Wifi5Soft]
Node= ESP8266
Version= 4.4
Part=1
Offseat=0x0000000
Wireless=True
LanBased=False

[VENDO_Wifi5Soft-ESP32]
Node= ESP32
Version= 4.4
Part=4
Offseat=0xe000,0x1000,0x10000,0x8000
Wireless=True
LanBased=False
